services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - NODE_VER=20.17.0
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/backend/node_modules
    ports:
      - "3000:3000"
    networks:
      - line-liff

networks:
  line-liff:
    external: true
volumes:
  node_modules:
