version: "3.7"
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.prod
    tty: true
    volumes:
      - ./backend:/home/node/app
      - node_modules:/home/node/app/node_modules
      - dist:/home/node/app/dist
    ports:
      - "3000:3000"

volumes:
  node_modules:
  dist:
