ARG NODE_VER
FROM node:20.10.0

USER node
WORKDIR /home/node/app

COPY --chown=node:node ./backend/package*.json ./
RUN npm install --porduction

COPY --chown=node:node ./backend/dist ./dist

EXPOSE 3000

ENTRYPOINT ["node", "dist/main.js"]