ARG NODE_VER
FROM node:20.10.0

RUN npm update -g npm
RUN npm i -g @nestjs/cli

USER node
WORKDIR /home/node/app

COPY --chown=node:node backend .

RUN npm install --production

RUN npm run build

EXPOSE 3000

ENTRYPOINT ["node", "dist/main.js"]