# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gcon-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io//
        username: ${{ secrets.AzureAppService_ContainerUsername_6af4d236f68f46f0921da1b57dfc9580 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cdafb55f4b7943cdbc7f0b0f44067001 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io//${{ secrets.AzureAppService_ContainerUsername_6af4d236f68f46f0921da1b57dfc9580 }}/ghcr.io/ryunosuke-tanaka-sti/line-liff-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gcon-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e16d4f98c4ac4eaebb0f259fa080dc1c }}
        images: 'ghcr.io//${{ secrets.AzureAppService_ContainerUsername_6af4d236f68f46f0921da1b57dfc9580 }}/ghcr.io/ryunosuke-tanaka-sti/line-liff-backend:${{ github.sha }}'